name: framework_base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.8
  - cairo=1.14.12
  - certifi=2020.12.5
  - ffmpeg=4.0.2
  - ffmpeg-python=0.2.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.10.4
  - future=0.18.2
  - glib=2.66.1
  - gmp=6.1.2
  - gnutls=3.5.19
  - graphite2=1.3.14
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2020.2
  - jasper=2.0.14
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.16
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - nettle=3.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - opencv=3.4.2
  - openh264=1.8.0
  - openssl=1.1.1i
  - pcre=8.44
  - pip=20.3.1
  - pixman=0.40.0
  - py-opencv=3.4.2
  - python=3.6.12
  - python_abi=3.6
  - readline=8.0
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tqdm=4.54.1
  - wheel=0.35.1
  - x264=1!152.20180806
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - image-slicer==2.1.1
    - pillow==7.2.0
