name: fastdvdnet
channels:
  - pytorch
  - serge-sans-paille
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - scikit-image=0.14.1=py36he6710b0_0
  - pip=19.0.1=py36_0
  - pip:
    - pytest==5.4.1
    - opencv-python==3.4.2.17
    - pycodestyle==2.5.0
    - torch==1.0.1.post2
    - future==0.18.2
    - tensorboardX==2.0